siren7.exe -e -7 all.wav all.s7 
siren7.exe -e -7 aunt_big.wav aunt_big.s7
siren7.exe -e -7 aunt_big_ch.wav aunt_big_ch.s7
siren7.exe -e -7 aunt_big_mo.wav aunt_big_mo.s7
siren7.exe -e -7 aunt_big_mo_ch.wav aunt_big_mo_ch.s7
siren7.exe -e -7 aunt_en.wav aunt_en.s7
siren7.exe -e -7 aunt_small.wav aunt_small.s7
siren7.exe -e -7 aunt_small_ch.wav aunt_small_ch.s7
siren7.exe -e -7 aunt_small_mo.wav aunt_small_mo.s7
siren7.exe -e -7 aunt_small_mo_ch.wav aunt_small_mo_ch.s7
siren7.exe -e -7 background.wav background.s7
siren7.exe -e -7 before_bus.wav before_bus.s7
siren7.exe -e -7 before_china.wav before_china.s7
siren7.exe -e -7 before_father.wav before_father.s7
siren7.exe -e -7 before_refrigerators.wav before_refrigerators.s7
siren7.exe -e -7 brother_big.wav brother_big.s7
siren7.exe -e -7 brother_big_ch.wav brother_big_ch.s7
siren7.exe -e -7 brother_big_com_ch.wav brother_big_com_ch.s7
siren7.exe -e -7 brother_en.wav brother_en.s7
siren7.exe -e -7 brother_small.wav brother_small.s7
siren7.exe -e -7 brother_small_ch.wav brother_small_ch.s7
siren7.exe -e -7 brother_small_com_ch.wav brother_small_com_ch.s7
siren7.exe -e -7 bus.wav bus.s7
siren7.exe -e -7 china.wav china.s7
siren7.exe -e -7 eg003.wav eg003.s7
siren7.exe -e -7 father.wav father.s7
siren7.exe -e -7 father_ch.wav father_ch.s7
siren7.exe -e -7 father_en.wav father_en.s7
siren7.exe -e -7 garden.wav garden.s7
siren7.exe -e -7 grandfahter_mo_ch.wav grandfather_mo_ch.s7
siren7.exe -e -7 grandfather.wav grandfather.s7
siren7.exe -e -7 grandfather_ch.wav grandfather_ch.s7
siren7.exe -e -7 grandfather_en.wav grandfather_en.s7
siren7.exe -e -7 grandfather_mo.wav grandfather_mo.s7
siren7.exe -e -7 grandmother.wav grandmother.s7
siren7.exe -e -7 grandmother_ch.wav grandmother_ch.s7
siren7.exe -e -7 grandmother_en.wav grandmother_en.s7
siren7.exe -e -7 grandmother_mo.wav grandmother_mo.s7
siren7.exe -e -7 grandmother_mo_ch.wav grandmother_mo_ch.s7
siren7.exe -e -7 gs002.wav gs002.s7
siren7.exe -e -7 me.wav me.s7
siren7.exe -e -7 me_ch.wav me_ch.s7
siren7.exe -e -7 me_en.wav me_en.s7
siren7.exe -e -7 mother.wav mother.s7
siren7.exe -e -7 mother_ch.wav mother_ch.s7
siren7.exe -e -7 mother_en.wav mother_en.s7
siren7.exe -e -7 music.wav music.s7
siren7.exe -e -7 pen_end.wav pen_end.s7
siren7.exe -e -7 pen_start.wav pen_start.s7
siren7.exe -e -7 refrigerators.wav refrigerators.s7
siren7.exe -e -7 sc004.wav sc004.s7
siren7.exe -e -7 shovel.wav shovel.s7
siren7.exe -e -7 sister_big.wav sister_big.s7
siren7.exe -e -7 sister_big_ch.wav sister_big_ch.s7
siren7.exe -e -7 sister_big_com_ch.wav sister_big_com_ch.s7
siren7.exe -e -7 sister_en.wav sister_en.s7
siren7.exe -e -7 sister_small.wav sister_small.s7
siren7.exe -e -7 sister_small_ch.wav sister_small_ch.s7
siren7.exe -e -7 sister_small_com_ch.wav sister_small_com_ch.s7
siren7.exe -e -7 uncle_big.wav uncle_big.s7
siren7.exe -e -7 uncle_big_ch.wav uncle_big_ch.s7
siren7.exe -e -7 uncle_big_mo.wav uncle_big_mo.s7
siren7.exe -e -7 uncle_big_mo_ch.wav uncle_big_mo_ch.s7
siren7.exe -e -7 uncle_en.wav uncle_en.s7
siren7.exe -e -7 uncle_small.wav uncle_small.s7
siren7.exe -e -7 uncle_small_ch.wav uncle_small_ch.s7
siren7.exe -e -7 uncle_small_mo.wav uncle_small_mo.s7
siren7.exe -e -7 uncle_small_mo_ch.wav uncle_small_mo_ch.s7